const SELF_DESCRIBED_GF = 3;
const HAS_GF_ITEMS = 2;
const COMMENTS_MENTION_GF = 1;
const NO_MENTION_GF = 0;
const MENU_NOT_ACCESSIBLE = -1;

module.exports = {SELF_DESCRIBED_GF, HAS_GF_ITEMS, COMMENTS_MENTION_GF, NO_MENTION_GF, MENU_NOT_ACCESSIBLE};